# Docker compose to run Go backend and Next frontend

services:
  backend:
    # Use Dockerfile in backend
    build: ./backend
    # Serve GraphQL at this port
    ports:
      - "8080:8080"
  frontend:
    # Use Dockerfile in frontend
    build: ./frontend
    # Serve Next app at this port
    ports:
      - "3000:3000"
    # Add LLM base URL to work in containers
    environment:
      - LLM_URL=http://host.docker.internal:1234/v1